In [63]:
print("hi")
print('bye')

hi
bye


In [2]:
import numpy as np

In [3]:
np_array=np.array([5,10,15,20,25])

In [5]:
sequence=np.arange(3)

In [6]:
print(sequence)

[0 1 2]


In [7]:
np_array.shape

(5,)

In [8]:
np_array.reshape

<function ndarray.reshape>

In [12]:
np.mean(np_array)

15.0

In [13]:
np.std(np_array)

7.0710678118654755

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.randint(np_array)

array([ 0,  7, 10, 18,  6])

In [22]:
np.random.rand(6,7)

array([[0.17409168, 0.30375778, 0.90611548, 0.63601334, 0.77974664,
        0.53002585, 0.10172623],
       [0.45403842, 0.82791619, 0.63415972, 0.84646834, 0.53479502,
        0.2030934 , 0.74145295],
       [0.99625878, 0.99703831, 0.68908094, 0.22652591, 0.37749785,
        0.5896042 , 0.90714809],
       [0.22352932, 0.31472727, 0.06037965, 0.79528893, 0.61697341,
        0.65672093, 0.13299862],
       [0.79169829, 0.73479632, 0.82156878, 0.77244951, 0.19192984,
        0.02753456, 0.70785944],
       [0.53808558, 0.74553692, 0.18556327, 0.50899295, 0.11994295,
        0.09939713, 0.72009537]])

In [24]:
np.random.randint(100,size=5)

array([59, 57, 30, 32, 54])

In [25]:
arr=np.array(['ball','cat','apple','orange'])

In [27]:
print(np.sort(arr))

['apple' 'ball' 'cat' 'orange']


In [28]:
arr1=np.array([5,25,3,9,18,20,30])

In [29]:
print(arr[1:4])

['cat' 'apple' 'orange']


In [30]:
print(arr1[1:6])

[25  3  9 18 20]


In [33]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [34]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.ones((6,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [36]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [40]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
import pandas as pd

In [45]:
data={
    "Products":['Laptop','mobile','mouse','monitor','keyboard'],
    "price":[1200,25,400,60,100],
"In_stock":[True,False,False,True,True]
}


In [46]:
print(data)

{'Products': ['Laptop', 'mobile', 'mouse', 'monitor', 'keyboard'], 'price': [1200, 25, 400, 60, 100], 'In_stock': [True, False, False, True, True]}


In [47]:
df = pd.DataFrame(data)
print(df)

   Products  price  In_stock
0    Laptop   1200      True
1    mobile     25     False
2     mouse    400     False
3   monitor     60      True
4  keyboard    100      True


In [48]:
company_data = {
    "Department": ["HR", "IT", "IT", "HR", "Sales"],
    "Salary": [50000, 80000, 95000, 55000, 70000]
}
df_company = pd.DataFrame(company_data)
avg_salary = df_company.groupby("Department")["Salary"].mean()
print(avg_salary)

Department
HR       52500.0
IT       87500.0
Sales    70000.0
Name: Salary, dtype: float64


In [49]:
print(df.loc[0])

Products    Laptop
price         1200
In_stock      True
Name: 0, dtype: object


In [50]:
result = df[df['price'] > 100]
print(result)

  Products  price  In_stock
0   Laptop   1200      True
2    mouse    400     False


In [51]:
df.describe()

,price
count,5.000000
mean,357.000000
std,494.211493
min,25.000000
25%,60.000000
50%,100.000000
75%,400.000000
max,1200.000000


In [56]:
df = pd.DataFrame(company_data)
result1 = df[df["Salary"] > 70000]
print(result1)

  Department  Salary
1         IT   80000
2         IT   95000


In [57]:
print(df.head())

  Department  Salary
0         HR   50000
1         IT   80000
2         IT   95000
3         HR   55000
4      Sales   70000


In [58]:
print(df.tail())

  Department  Salary
0         HR   50000
1         IT   80000
2         IT   95000
3         HR   55000
4      Sales   70000


In [59]:
print(df.sort_values(by="Salary"))

  Department  Salary
0         HR   50000
3         HR   55000
4      Sales   70000
1         IT   80000
2         IT   95000


In [62]:
print(df["Department"].value_counts())

Department
HR       2
IT       2
Sales    1
Name: count, dtype: int64
